clone:
  git:
    image: plugins/git

pipeline:
  install: &install
    image: rappdw/docker-java-python
    commands:
      - make drone-install

  style-check:
    <<: *install
    commands:
      - PYTHONPATH=./pip/deps make style-check
    when:
      event: push

  check-flake8:
    <<: *install
    commands:
      - PYTHONPATH=./pip/deps make check-flake8
    when:
      event: push

  unit-tests:
    <<: *install
    commands:
      - PYTHONPATH=./pip/deps make unit-tests
    when:
      event: push

  integration-tests:
    <<: *install
    commands:
      - PYTHONPATH=./pip/deps make integration-tests
    when:
      event: push

  package:
    <<: *install
    commands:
      - PYTHONPATH=./pip/deps make package
    when:
      event: tag
      branch: master

  pypi-release:
    <<: *install
    commands:
      - pip install twine==3.1.1
      - twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD --verbose dist/*
    secrets: [ pypi_username, pypi_password ]
    when:
      event: tag
      branch: master
